// Guest list imported from "Chad + Eric Wedding Planner.xlsx" (Guests tab) on 2026-10-01.
const WEDDING_GUESTS = [
  { first: "Ashlee", last: "Heller", side: "Chad's Side", priority: "Must", table: "Grooms Party (1)" },
  { first: "Tyler", last: "Canales", side: "Chad's Side", priority: "Must", table: "Heller Family (2)" },
  { first: "Shawn", last: "Heller", side: "Chad's Side", priority: "Must", table: "Heller Family (2)" },
  { first: "Barbara", last: "Heller", side: "Chad's Side", priority: "Must", table: "Heller Family (2)" },
  { first: "Adriel", last: "Barrera", side: "Chad's Side", priority: "Must", table: "Grooms Party (1)" },
  { first: "Aleah", last: "Barrea", side: "Chad's Side", priority: "Must", table: "Barrera Family (5)" },
  { first: "Haydee", last: "Barrera", side: "Chad's Side", priority: "Must", table: "Barrera Family (5)" },
  { first: "Miguel", last: "Barrera", side: "Chad's Side", priority: "Must", table: "Barrera Family (5)" },
  { first: "Andrew", last: "Barrera", side: "Chad's Side", priority: "Must", table: "Barrera Family (5)" },
  { first: "Jennilee", last: "Arriaga", side: "Chad's Side", priority: "Must", table: "Grooms Party (1)" },
  { first: "Luis", last: "Arriaga", side: "Chad's Side", priority: "Must", table: "Tamplen Party (9)" },
  { first: "Lauralee", last: "Tamplen", side: "Chad's Side", priority: "Must", table: "Tamplen Party (9)" },
  { first: "Emily", last: "McGee", side: "Chad's Side", priority: "Must", table: "Tamplen Party (9)" },
  { first: "Britney", last: "Rich", side: "Chad's Side", priority: "Must", table: "Tamplen Party (9)" },
  { first: "Aaron", last: "Rich", side: "Chad's Side", priority: "Must", table: "Tamplen Party (9)" },
  { first: "Clarissa", last: "Debastiani", side: "Chad's Side", priority: "Must", table: "Friends (7)" },
  { first: "Cody", last: "Debastiani", side: "Chad's Side", priority: "Must", table: "Friends (7)" },
  { first: "Elena", last: "Herrera", side: "Chad's Side", priority: "Must", table: "Barrera Family (5)" },
  { first: "Seth", last: "Herrera", side: "Chad's Side", priority: "Must", table: "Barrera Family (5)" },
  { first: "Lulu", last: "Lu", side: "Chad's Side", priority: "Must", table: "Friends (7)" },
  { first: "Angela", last: "Avila", side: "Chad's Side", priority: "Must", table: "Friends (7)" },
  { first: "Bill", last: "Renton", side: "Chad's Side", priority: "Must", table: "Heller Family (2)" },
  { first: "Rick", last: "", side: "Chad's Side", priority: "Must", table: "Heller Family (2)" },
  { first: "Donald Jr.", last: "Heller", side: "Chad's Side", priority: "Optional", table: "Heller Family pt. 2 (11)" },
  { first: "Valerie", last: "Heller", side: "Chad's Side", priority: "Optional", table: "Heller Family pt. 2 (11)" },
  { first: "Andrea", last: "Carrizales", side: "Chad's Side", priority: "Must", table: "Heller Family pt. 2 (11)" },
  { first: "David", last: "Carrizales", side: "Chad's Side", priority: "Must", table: "Heller Family pt. 2 (11)" },
  { first: "Lindsay", last: "Turner", side: "Chad's Side", priority: "Optional", table: "Heller Family pt. 2 (11)" },
  { first: "Clint", last: "Turner", side: "Chad's Side", priority: "Optional", table: "Heller Family pt. 2 (11)" },
  { first: "Nancy", last: "Carpenter", side: "Chad's Side", priority: "Optional", table: "Heller Family (2)" },
  { first: "Stephanie", last: "Carter", side: "Chad's Side", priority: "Optional", table: "Heller Family (2)" },
  { first: "Rebecca", last: "Martinez", side: "Chad's Side", priority: "Must", table: "Friends (7)" },
  { first: "Aide", last: "Funes", side: "Chad's Side", priority: "Must", table: "Friends (7)" },
  { first: "Daniel", last: "Evelyn", side: "Chad's Side", priority: "Must", table: "Friends (7)" },
  { first: "Jessica", last: "Shrope", side: "Chad's Side", priority: "Must", table: "Barrera Family (5)" },
  { first: "Allison", last: "Varella", side: "Chad's Side", priority: "Must", table: "Barrera Family (5)" },
  { first: "Chyanne", last: "Biondo", side: "Chad's Side", priority: "Must", table: "Heller Family pt. 2 (11)" },
  { first: "Addison", last: "Biondo", side: "Chad's Side", priority: "Must", table: "Heller Family pt. 2 (11)" },
  { first: "Johanna", last: "Escobar", side: "Eric's Side", priority: "Must", table: "Escobar Family (3)" },
  { first: "Shawn", last: "Wilkins", side: "Eric's Side", priority: "Must", table: "Escobar Family (3)" },
  { first: "Fredy", last: "Escobar", side: "Eric's Side", priority: "Must", table: "Escobar Family (3)" },
  { first: "Sonia", last: "Escobar", side: "Eric's Side", priority: "Must", table: "Escobar Family (3)" },
  { first: "Conchita", last: "Espinosa", side: "Eric's Side", priority: "Must", table: "Escobar Family (3)" },
  { first: "Mari", last: "Espinosa", side: "Eric's Side", priority: "Must", table: "Escobar Family (3)" },
  { first: "Jo Angel", last: "Herrera", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 2 (4)" },
  { first: "Cindy", last: "Escobar", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 2 (4)" },
  { first: "Sawyer", last: "Wilkins", side: "Eric's Side", priority: "Must", table: "Escobar Family (3)" },
  { first: "Sofia", last: "Wilkins", side: "Eric's Side", priority: "Must", table: "Escobar Family (3)" },
  { first: "Logan", last: "Herrera", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 2 (4)" },
  { first: "Lilliana", last: "Escobar", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 2 (4)" },
  { first: "Alex", last: "Benevides", side: "Eric's Side", priority: "Must", table: "Benevides Family (6)" },
  { first: "Salma", last: "Benevides", side: "Eric's Side", priority: "Must", table: "Benevides Family (6)" },
  { first: "Maricela", last: "Benevides", side: "Eric's Side", priority: "Must", table: "Benevides Family (6)" },
  { first: "Alonzo", last: "Benevides", side: "Eric's Side", priority: "Must", table: "Benevides Family (6)" },
  { first: "Macy", last: "Portillo", side: "Eric's Side", priority: "Must", table: "Grooms Party (1)" },
  { first: "Gabe", last: "Portillo", side: "Eric's Side", priority: "Must", table: "Grooms Party (1)" },
  { first: "Julisa", last: "Bosquez", side: "Eric's Side", priority: "Must", table: "Grooms Party (1)" },
  { first: "Javier", last: "Escobar", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 2 (4)" },
  { first: "Andrea", last: "Salazar", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 2 (4)" },
  { first: "Sharon", last: "Coburn", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 3 (8)" },
  { first: "Ralph", last: "Coburn", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 3 (8)" },
  { first: "Steph", last: "Benevides", side: "Eric's Side", priority: "Must", table: "Benevides Family (6)" },
  { first: "Steph", last: "Giuffria", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 3 (8)" },
  { first: "PJ", last: "Giuffria", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 3 (8)" },
  { first: "Kiddo", last: "Giuffria", side: "Eric's Side", priority: "Must", table: "Escobar Family pt. 3 (8)" },
  { first: "Diego", last: "De Leon", side: "Eric's Side", priority: "Must", table: "Benevides Family (6)" },
  { first: "Gabby", last: "Madrigal", side: "Eric's Side", priority: "Must", table: "Friends (7)" },
  { first: "Rosie", last: "Casanova", side: "Eric's Side", priority: "Must", table: "Friends (7)" }
].map(g => ({ ...g, inviteSent: false, rsvp: "Pending" }));
